version: '3'

networks:
  api-network:
    driver: bridge

services:
  laravel-api:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: laravel-api
    ports: 
      - "8000:80"
    volumes: 
      - ./src:/usr/share/nginx
    networks: 
      - api-network

  mysql-api:
    image: mysql:5.7
    container_name: mysql-api
    command: --innodb-use-native-aio=0
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: 123senha
      MYSQL_ROOT_PASSWORD: 123senha
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - api-network
    volumes: 
      - ./mysql:/var/lib/mysql